mpirun -np 3 \
-bind-to none \
-map-by slot \
-mca pml ob1 -mca btl ^openib \
python train_mpi.py \
--wandb_project Test_style_pretrained_Bs0.8 \
--dataset pacs \
--use_style_stats \
--datasetRoot ../datasets/ \
--leave_out art_painting \
--graphid -1 \
--lr 0.001 \
--bs 64 \
--epoch 80 \
--budget 1.0 \
--momentum 0.9 \
-n Vanilla_DecenSGD \
--model res \
--resnet_type standard \
-p \
--description Vanilla_DecenSGD_PACS_experiment \
--savePath ./exp_result_ \
--randomSeed 1234 \
--use_style_shift \
--pretrained \
--style_shift_prob 0.8 \
--style_shift_ratio 0.5 \